### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by AnthonyBronca** [AnthonyBronca/japan-travel-app#2]
# To Do List

## Summary
A way for users to manage their todo list items. They should be able to scroll through the items, click on one particular to do item, and also create items.

## Features

- [ ] Ability to create a todo list item (button leading to a form modal)
- [ ] Ability to scroll through to-do list items (scrollable)
- [ ] Ability to click on a to-list item and see it in full (on press)
- [ ] Ability to edit a todo item (on swipe left)
- [ ] Ability to delete a todo item (on swipe left)

## Future feature considerations (NON MVP)
- [ ] Ability to share todo list items (requires internet)
- [ ] Ability to receive todo list items (requires internet)
- [ ] Ability to pin todo list items at the top
- [ ] Ability to add images to list (may require internet if using AWS)
